import React, { useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
import Cards from 'components/CoreReuseAbleComponents/PostComponents/componentsMapper'
import TopTabs from 'components/CoreReuseAbleComponents/CoreTabs'

const Home = () => {
  const topTabs = ['GENERAL', 'FOLLOWING']
  const [topTab, setTopTab] = useState('GENERAL')
  const [posts, setPosts] = useState([
    {
      id: 0,
      userName: 'Tomas.thena',
      userImage: '/images/core/p3.png',
      repostedUserName: 'Johndoe.thena',
      repsotedTime: '3 min ago',
      likes: 0,
      comments: [
        {
          commentId: 211,
          timePassed: '22 min ago',
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          userName: 'Tomas.thena',
          userComment: true,
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '2 min ago',
      type: 'info',
      svg: '/images/core/add-liquidity.svg',
      info: 'Larathompson.thena has removed 10 USDT & 10 USDC from the USDT-USDC stable liquidity pool.',
    },
    {
      id: 111,
      userName: 'Tomas.thena',
      userImage: '/images/core/p3.png',
      likes: 0,
      comments: [],
      timePassed: '2 min ago',
      type: 'nft',
      nftImage: '/images/profile/nfts/thenft.png',
      title: 'Thenian #518',
      info: "<p>Price on OpenSea <span id='price'>0.1 BNB</span> $23.05</p>",
    },
    {
      id: 1,
      userName: 'Xermes.thena',
      userImage: '/images/core/p3.png',
      likes: 3,
      comments: [
        {
          commentId: 2,
          timePassed: '22 min ago',
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '2 min ago',
      type: 'badge',
      info: 'Rising Star Achievement Completed!',
      reason: 'Reach a trading volume of $25,000 USD.',
      icon: 'https://cdn.thena.fi/assets/DOGE.png',
    },
    {
      id: 2,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 4,
      comments: [
        {
          commentId: 4,
          timePassed: '2 min ago',
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '',
          userName: 'Xermes',
          userImage: '/images/core/p1.png',
          likes: 8,
          replies: [
            {
              commentId: 3,
              userName: 'Xermes.thena',
              userImage: '/images/core/p2.png',
              comment: 'Lorem ipsum dolor sit amet.',
              commentImage: '/images/core/cover.png',
              timePassed: '2 min ago',
              likes: 8,
            },
            {
              commentId: 7,
              userName: 'Xermes.thena',
              userImage: '/images/core/p1.png',
              comment: 'Lorem ipsum dolor sit amet.',
              commentImage: '/images/core/cover.png',
              timePassed: '2 min ago',
              likes: 8,
            },
          ],
        },
        {
          commentId: uuidv4(),
          timePassed: '22 min ago',
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          userName: 'Larathomspon.thena',
          userComment: true,
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '4 min ago',
      type: 'competitionpost',
      tradingType: 'PERPETUAL',
      info: "<p>Xermes.thena created trading competition <a href='/core/competition/trading-competition-1'>Trading Competition 4.</a></p>",
      title: 'Ankr Discord AMA',
      time: 'Fri, Jan 27, 2023, 1 PM UTC',
      members: 246,
      money: '$9,460',
      free: true,
      postImg: '/images/core/cover.png',
    },
    {
      id: 3,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 10,
      comments: [
        {
          commentId: 6,
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '2 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p1.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '2 min ago',
      type: 'info',
      svg: '/images/core/add-liquidity.svg',
      info: 'Larathompson.thena has removed 10 USDT & 10 USDC from the USDT-USDC stable liquidity pool.',
    },
    {
      id: 4,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 11,
      comments: [
        {
          commentId: 8,
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '2 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [
            {
              commentId: 9,
              userName: 'Xermes.thena',
              userImage: '/images/core/p3.png',
              comment: 'Lorem.',
              commentImage: '/images/core/cover.png',
              timePassed: '2 min ago',
              likes: 8,
            },
          ],
        },
      ],
      timePassed: '20 min ago',
      type: 'info',
      svg: '/images/core/bribe.svg',
      info: 'Tomas.thena bribed USDC-USDT stable with 100 USDC, 50 BNB.',
    },
    {
      id: 5,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 12,
      comments: [
        {
          commentId: 10,
          comment: 'Lorem  dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '1 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '30 min ago',
      type: 'competitionpost',
      tradingType: 'SPOT',
      info: "<p>Xermes.thena created trading competition <a href='/core/competition/trading-competition-1'>Trading Competition 4.</a></p>",
      title: 'Ankr Discord AMA',
      time: 'Fri, Jan 27, 2023, 1 PM UTC',
      members: 246,
      money: '$9,460',
      free: false,
      fee: 200,
      postImg: '/images/core/cover.png',
    },
    {
      id: 6,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 6,
      comments: [
        {
          commentId: 12,
          comment: 'ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '1 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
        {
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '2 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '10 min ago',
      type: 'info',
      svg: '/images/core/pool.svg',
      info: 'Tomas.thena has created a new Liquidity Bootstrapping Pool myToken-WBNB.',
    },
    {
      id: 7,
      userName: 'Larathomspon.thena',
      userImage: '/images/core/p3.png',
      likes: 2,
      comments: [
        {
          commentId: 14,
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '2 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p3.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '10 min ago',
      type: 'info',
      svg: '/images/core/vote.svg',
      info: 'Tomas.thena has voted for USDT-WBNB, ETH-WBNB with weights 30%, 70%.',
    },
    {
      id: 8,
      userName: 'Tomas.thena',
      userImage: '/images/core/p3.png',
      likes: 12,
      comments: [
        {
          commentId: 16,
          comment: 'Lorem ipsum dolor.',
          commentImage: '',
          timePassed: '2 min ago',
          userName: 'Xermes.thena',
          userImage: '/images/core/p2.png',
          likes: 8,
          replies: [],
        },
      ],
      timePassed: '40 min ago',
      type: 'info',
      svg: '/images/core/swap.svg',
      info: 'Larathompson.thena has swapped 1,000 BUSD for 320 THE.',
    },
    {
      id: 9,
      userName: 'Xermes.thena',
      userImage: '/images/core/p3.png',
      likes: 10,
      comments: [
        {
          commentId: 18,
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '',
          timePassed: '12 min ago',
          userName: 'test.thena',
          userImage: '/images/core/p2.png',
          likes: 4,
          replies: [
            {
              commentId: 11,
              commentImage: '',
              timePassed: '12 min ago',
              userName: 'Xermes.thena',
              userImage: '/images/core/p2.png',
              comment: 'example 1.',
              likes: 2,
            },
            {
              commentId: 13,
              commentImage: '',
              timePassed: '12 min ago',
              userName: 'Xermes.thena',
              userImage: '/images/core/p1.png',
              comment: 'example 2.',
              likes: 1,
            },
          ],
        },

        {
          commentId: 20,
          comment: 'Lorem ipsum dolor sit amet.',
          commentImage: '/images/core/cover.png',
          timePassed: '12 min ago',
          userName: 'test.thena',
          userImage: '/images/core/p2.png',
          likes: 4,
          replies: [
            {
              commentId: 15,
              commentImage: '',
              timePassed: '12 min ago',
              userName: 'Xermes.thena',
              userImage: '/images/core/p2.png',
              comment: ' 1.',
              likes: 2,
            },
            {
              commentId: 17,
              commentImage: '/images/core/cover.png',
              timePassed: '12 min ago',
              userName: 'Xermes.thena',
              userImage: '/images/core/p1.png',
              comment: ' 2.',
              likes: 1,
            },
          ],
        },
      ],
      timePassed: '13 min ago',
      type: 'eventpost',
      info: '<p>Larathomspon.thena attends event <a href=\'https://discord.gg/yaka-finance/\' target="__blank">Ankr Discord AMA.</a></p>',
      title: 'Ankr Discord AMA',
      time: 'Fri, Jan 27, 2023, 1 PM UTC',
      members: 246,
      money: '$9,460',
      free: false,
      fee: 200,
      duration: '1h 20m',
      location: 'Ankr Discord',
      postImg: '/images/core/cover.png',
      locationLink: 'https://discord.gg/yaka-finance/',
    },
  ])
  return (
    <div className='w-full  2xl:max-w-full'>
      <TopTabs home tabs={topTabs} setTab={setTopTab} tab={topTab} />
      <Cards home setPosts={setPosts} posts={posts} />
    </div>
  )
}

export default Home
